version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "raravena80"
    assignees:
      - "raravena80"
    commit-message:
      prefix: "cargo"
      prefix-development: "cargo"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignore major version updates for core dependencies
      # that might require significant code changes
      - dependency-name: "openraft"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actix-web"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rocksdb"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "ci" 
